/control/verbose 2
/run/initialize

/tracking/verbose 1
/tracking/storeTrajectory 1 
/tracking/verbose 0
 

#/score/create/boxMesh boxMesh_1
#/score/mesh/translate/xyz 0 0 130 mm
#/score/mesh/boxSize 127.5 127.5 127.5 mm  # half dim
#/score/mesh/nBin 51 51 51
#/score/quantity/doseDeposit dDep
#/score/close
#/score/list

#
/run/printProgress 10
/run/beamOn 50

#/score/drawProjection boxMesh_1 dDep
#/score/dumpQuantityToFile boxMesh_1 dDep dDep.txt
